# Generated by Django 5.2.4 on 2025-07-15 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_reward_tablesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='business',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='game',
            name='win_probability',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='game',
        ),
        migrations.AlterField(
            model_name='business',
            name='ip_range',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='BusinessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_probability', models.FloatField(help_text='0 ile 1 arasında bir oran')),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
            ],
            options={
                'unique_together': {('business', 'game')},
            },
        ),
        migrations.AddField(
            model_name='reward',
            name='business_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='core.businessgame'),
        ),
        migrations.CreateModel(
            name='GameAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_code', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('won', models.BooleanField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('business_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='core.businessgame')),
            ],
        ),
        migrations.DeleteModel(
            name='TableSession',
        ),
    ]
