# Generated by Django 5.2.4 on 2025-07-15 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_business_ip_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplay',
            name='business',
        ),
        migrations.RemoveField(
            model_name='gameplay',
            name='game',
        ),
        migrations.AddField(
            model_name='gameplay',
            name='business_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.businessgame'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
