# Generated by Django 5.2.4 on 2025-07-15 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_gameplay_business_remove_gameplay_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplay',
            name='business_game',
        ),
        migrations.AddField(
            model_name='gameplay',
            name='business',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.business'),
        ),
        migrations.AddField(
            model_name='gameplay',
            name='game',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
