# Generated by Django 5.2.4 on 2025-07-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_gameplay_business_game_gameplay_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='daily_game_limit_per_ip',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
