# Generated by Django 5.2.4 on 2025-07-15 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_business_created_at_remove_game_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='ip_range',
        ),
        migrations.RemoveField(
            model_name='businessgame',
            name='is_active',
        ),
        migrations.AddField(
            model_name='business',
            name='network_ip_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='unique_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businessgame',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_games', to='core.business'),
        ),
        migrations.AlterField(
            model_name='businessgame',
            name='win_probability',
            field=models.FloatField(help_text='0.0 - 1.0 arası kazanma olasılığı'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('result', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
            ],
        ),
        migrations.DeleteModel(
            name='GameAccessLog',
        ),
    ]
