# Generated by Django 5.2.4 on 2025-07-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_business_daily_game_limit_per_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='daily_game_limit_per_ip',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
